### ISSUE TITLE
推流时，在拉流端收不到声音

### ISSUE THREAD

**Issue by silent-shawn** [fyuoo/webrtc_srs_win_demo#1]
大佬，你好，感谢你开源的代码。
我在使用测试时发现一个问题，就是在拉流端接收这个demo推的流时，有画面但没有声音，请问你有这种问题吗？
我这边的编译环境vs2022 + 10.0.22621
测试过SRS5.0，和6.0的最新版本，都有这样的问题
1. c++推流，不管c++拉流还是web拉流，都是有画面但没有声音
2. web推流，c++拉流还是web拉流，都是有画面也有声音
3. 测试webrtc自带的peer_connection_demo, 有画面也有声音

所以推测是不是在推流时声音没有推上去？

**Comment by yanjing2407** [comment]
同样的问题，截包发现，就是没有推流上去，有视频包没有音频包，目前还没找到解决办法，求大佬指点

**Comment by fyuoo** [comment]
strtc_media_stream.cc中先关闭回声消除，看着是这个引起音频采集失败
```
if (has_audio_) {
    cricket::AudioOptions options;
    options.echo_cancellation = false; //添加
    rtc::scoped_refptr<webrtc::AudioSourceInterface> source =
        factory_->CreateAudioSource(options);
  }
```
